feat(bat): Move config files to default directory on windows

diff --git a/run_once_after_install-packages-darwin.sh.tmpl b/run_once_after_install-packages-darwin.sh.tmpl
--- a/run_once_after_install-packages-darwin.sh.tmpl
+++ b/run_once_after_install-packages-darwin.sh.tmpl
@@ -2,55 +2,55 @@
 #!/bin/sh
 
 AssertCommandInstalled() {
-	installed_command=$1
-	if ! command -v $installed_command &>/dev/null; then
-		echo "$installed_command could not be found"
-		exit 1
-	fi
+  installed_command=$1
+  if ! command -v $installed_command &>/dev/null; then
+    echo "$installed_command could not be found"
+    exit 1
+  fi
 }
 
 BrewInstall() {
-	package=$1
-	AssertCommandInstalled "brew"
-	if ! brew ls --versions $package >/dev/null; then
-		brew install $package
-	fi
+  package=$1
+  AssertCommandInstalled "brew"
+  if ! brew ls --versions $package >/dev/null; then
+    brew install $package
+  fi
 }
 
 CargoInstall() {
-	package=$1
-	AssertCommandInstalled "cargo"
-	cargo install --locked $package
+  package=$1
+  AssertCommandInstalled "cargo"
+  cargo install --locked $package
 }
 
 CargoBInstall() {
-	package=$1
-	AssertCommandInstalled "cargo help binstall"
-	cargo binstall --secure $package
+  package=$1
+  AssertCommandInstalled "cargo help binstall"
+  cargo binstall --secure $package
 }
 
 RustupAddComponent() {
-	component=$1
-	AssertCommandInstalled "rustup"
-	rustup component add $component
+  component=$1
+  AssertCommandInstalled "rustup"
+  rustup component add $component
 }
 
 ExecuteCallbackOnList() {
-	callback=$1
-	list=$2
-	while read line; do
-		case "$line" in
-		"")
-			continue
-			;;
-		\#*)
-			continue
-			;;
-		*)
-			$callback $line
-			;;
-		esac
-	done <$list
+  callback=$1
+  list=$2
+  while read line; do
+    case "$line" in
+    "")
+      continue
+      ;;
+    \#*)
+      continue
+      ;;
+    *)
+      $callback $line
+      ;;
+    esac
+  done <$list
 }
 
 brew upgrade
@@ -66,5 +66,8 @@ ExecuteCallbackOnList CargoInstall "$HOME/.config/chezmoi/cargo_install_packages
 
 # Add rustup components
 ExecuteCallbackOnList RustupAddComponent "$HOME/.config/chezmoi/rustup_component_list.txt"
+
+# Bat settings
+bat cache --build
 
 {{- end -}}
